tools:
    php_analyzer: true
    external_code_coverage: true

filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - 'app/*'
        - 'bin/*'
        - 'library/*'
    paths: {  }
tools:
    php_analyzer:
        enabled: true
        extensions:
            - php
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
                - 'library/*'
            paths: {  }
        path_configs: {  }
    php_cpd:
        enabled: true
    external_code_coverage:
        enabled: true
        excluded_dirs: {  }
        names:
            - '*.php'
        min_lines: 5
        min_tokens: 70
        timeout: 300
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
                - 'library/*'
            paths: {  }
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
                - 'library/*'
            paths: {  }
            excluded_paths: {  }

changetracking:
    bug_patterns:
        - '\bfix(?:es|ed)?\b'
