language: php
services:
  - mysql
php:
  - 5.5
  - 5.4
  - 5.3
script: phpunit --coverage-clover=coverage.clover
before_script:
# pear.phpunit.de offline, and travis have phpunit 
#  - pear channel-discover pear.phpunit.de
#  - pear install phpunit/DbUnit
  - mysql -e 'create database alternc_test;'
  - cd phpunit
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
